### ISSUE TITLE
terminate called after throwing an instance of 'std::system_error'

### ISSUE THREAD

**Issue by AEEldin** [alexge233/semanet#1]
I followed the instructions you mentioned to build and compile, and except your comment: "Don't forget to link against libsmnet-0.1.so!" 
how & where to do this? as am getting this message "terminate called after throwing an instance of 'std::system_error'", when trying to run ./hyponym car

**Comment by alexge233** [comment]
This is a problem with WordNet, and in specific the function `wninit()`.
Have you installed the datasets correctly?

**Comment by AEEldin** [comment]
i used
sudo apt-get install wordnet
sudo apt-get install wordnet-dev

**Comment by alexge233** [comment]
Can you verify that wordnet works right out of the box?
e.g.:

```
wn "car" -hypen
```

**Comment by AEEldin** [comment]
wordnet itself is working, i think what am missing is your comment of:
"Don't forget to link against libsmnet-0.1.so!"

how & where to do this?

**Comment by alexge233** [comment]
The executables already link with libsmnet unless you're talking about your own app.
Let me run it through the debugger today on an Ubuntu machine, and I'll get back to you.

**Comment by alexge233** [comment]
Hi, the problem is `std::call_once`.
Just found the [root of the problem](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55394#c4):

```
clang's libc++.so.1 avoids the issue because it is linked with libpthread.so.0:

 % ldd /usr/lib/libc++.so.1
        linux-vdso.so.1 (0x00007ffc1618f000)
        libpthread.so.0 => /lib/libpthread.so.0 (0x00007fe0f4fd7000)
        libc.so.6 => /lib/libc.so.6 (0x00007fe0f4c3a000)
        libm.so.6 => /lib/libm.so.6 (0x00007fe0f499f000)
        librt.so.1 => /lib/librt.so.1 (0x00007fe0f4797000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x00007fe0f477e000)
        /lib64/ld-linux-x86-64.so.2 (0x00005575a195e000)

libstc++ isn't:

 % ldd /usr/lib/gcc/x86_64-pc-linux-gnu/7.0.0/libstdc++.so.6
        linux-vdso.so.1 (0x00007ffd14540000)
        libm.so.6 => /lib/libm.so.6 (0x00007f73bec87000)
        libc.so.6 => /lib/libc.so.6 (0x00007f73be8ea000)
        /lib64/ld-linux-x86-64.so.2 (0x00005594a5a06000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x00007f73be8d1000)
```

That's why it didn't crash in OSX, not sure though why it didn't crash under Debian...
I'll try to fix it tomorrow.

**Comment by alexge233** [comment]
@AEEldin Paul just fixed it.
